### ISSUE TITLE
prefix option

### ISSUE THREAD

**Issue by flippyhead** [aaronblohowiak/Push-It#5]
I assume this was removed and is no longer used? If so, how is the socket.io information distinguished ?

Thanks!

**Comment by aaronblohowiak** [comment]
options.hostname is passed through to the Socket.io instance.  Since the socket.io people made it so that socket.io will serve up its own client js and swf (if swf is needed,) i thought it might be more convenient to just let the default socket.io handlers take care of serving that material.  If you are using a cdn or similar, I'll add it back in.

Thanks!
